<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pages')->insert([
            [
                'id' => Str::uuid(), 
                'title' => 'Structure and Partners',
                'slug' => 'structure-and-partners',
                'order' => 1,
                'subtitle' => 'Structure and Partners',
                'body' => '<p>The Foundation has 9 members of Executive Committee that is providing strategic directions, instructions and approval for policy &amp; decision making which guide to implement the planned interventions in the community.</p><p><br></p><p>The Foundation has workforce to implement the day-to-day activities with effectively. There are; Executive Director, Operations Director, Program Coordinator, Youth Coordinator, Finance &amp; Admin Officer and volunteer(s). In addition, the Foundation deploy other staffs based on project/ specific objectives.</p><p>The Foundation is following partnering approach to implement the activities aiming to create ownership in the community. The partners are the community, elite persons, teachers, schools, different youth organizations, different cooperatives and NGOs. The Dhaka Credit is playing key role as partner and donor as well.</p><p>The main office of the “Dhaka Credit” at Dhaka and 12 branch offices are located at strategic points in four districts of Dhaka Division. It provides venue for meeting/training to its hall rooms. The Foundation implements the planned activities in the working area through collaborating with different youth organizations, cooperatives.</p><h2><strong>Donors</strong></h2><p><strong>CCCUL:&nbsp;</strong>The Christian Cooperative Credit Union Limited, Dhaka is popularly known Dhaka Credit has established Fr. Charles J. Young Foundation (FCJYF) in 2019. Dhaka Credit donated obligatory fund to the Fr. Charles J. Young Foundation. The Foundation is continuing its planned interventions through this fund and Individual &amp; personal sponsorship.</p>',
                'summary' => null,
                'button_text' => null, 
                'button_link' => null, 
                'attachment_url' => null, 
                'attachment_path' => null, 
                'attachment_name' => null, 
                'attachment_mime' => null, 
                'publish_status' => 'Published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(), 
                'title' => 'Chairman Message',
                'slug' => 'chairman-message',
                'order' => 2,
                'subtitle' => 'Message from the Chairman',
                'body' => '<p>This is my immense pleasure to inform you that I am nominated as Chairman of Fr. Charles J. Young Foundation as per Memorandum of Association and Articles of Association. The Christian Cooperative Credit Union Limited, Dhaka established Fr. Charles J. Young Foundation in 2019 to come into reality of vision of Rev. Fr. Charles J. Young, CSC who is pioneer of Credit Union Movement in Bangladesh and the Founder of The Christian Cooperative Credit Union Limited, Dhaka which is popularly known Dhaka Credit. The vision of late Fr. Charles J. Young, CSC was to poverty free community in Bangladesh. But due to legal compelling reason, Dhaka Credit could not reach who are suffering from different crisis. So, Dhaka Credit established separate entity for development works in different locations irrespective of caste, creed, religion of the community. The Foundation obtained registration from Registrar of Joint Stock Company in 2020 and NGO Affairs Bureau, Government of Bangladesh in 2023. Now it opens all the windows to implement development interventions with foreign donations in its working area. It is mentioned that, Dhaka Credit donated obligatory fund to its sister concern and continue its program at Dhaka, Gazipur, Narayanganj &amp; Munshiganj Districts. At the moment, Foundation has taken special initiative to make strategic relationship with various institutions and organizations. We are implementing education, health, youth development, assistance for technical &amp; vocational education, cultural programs. The Foundation already completed Socio-economic Baseline survey in four districts. And also planning for research program.</p><p>We trust that the Foundation will be able to continue its development efforts directive irrespective of caste creed and religion.</p><p>We accept donations from individual &amp; corporate to provide education assistance for the poor and meritorious students.</p><p>May all of you be happy, healthy and prosperous in your day-to-day life.</p><p>With thanks and best regards.</p><p>Ignatious Hemanta Corraya</p><p>Chairman, Fr. Charles J. Young Foundation</p>',
                'summary' => null,
                'button_text' => null, 
                'button_link' => null, 
                'attachment_url' => null, 
                'attachment_path' => null, 
                'attachment_name' => null, 
                'attachment_mime' => null, 
                'publish_status' => 'Published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(), 
                'title' => 'Our History',
                'slug' => 'our-history',
                'order' => 3,
                'subtitle' => 'History of Father Charles Joseph Young Foundation',
                'body' => '<p>Rev. Father Charles Joseph Young, CSC (1904-1988) who is the pioneer of the credit union movement in Bangladesh and the founder of The Christian Co-operative Credit Union Ltd, Dhaka (CCCUL), now popularly known as the “Dhaka Credit”.</p><p><br></p><p>Father Charles came to Bangladesh in 1933 worked in Dhaka and Mymensingh in several roles. He was shocked to see the financial condition of community in Bangladesh. They used to borrow money from Kabuliwalas which could not be repaid properly. Seeing this situation, he was very upset and dreamed of a society which free from hunger and poverty.</p><p>The vision has come into reality through establishing The Christian Co-operative Credit Union ltd, Dhaka in 1955 with 50 members only. In 2024, the number of the Members of the Dhaka Credit is around 46,000. The Christian Co-operative Credit Union ltd, Dhaka is operating its activities among the Christian community as per its bye-laws in Dhaka, Gazipur, Narayanganj and Munshiganj districts for improving the standard of living. It is realized that, Dhaka Credit could not reach with its activities beyond the Christian community under jurisdiction of its working area though there are many people are facing same sufferings for their livelihood.</p><p>In 2019, the then Executive Committee of The Christian Cooperative Credit Union Limited, Dhaka led by its President Mr. Babu Markus Gomes, decided to establish a Foundation in remembrance of Fr. Charles J. Young, CSC to spread out the development initiatives irrespective of caste, creed and religion under jurisdiction of its working area.</p><p>On August 17,2019, the “Fr. Charles J. Young Foundation” was established to fulfill the dream of Rev. Father Charles J. Young, CSC through conduct research on co-operative, educational supports to poor &amp; meritorious students for higher education, provide technical vocational education, women empowerment and youth development.</p><p>The First Executive Board of the “Fr. Charles J. Young Foundation” consists of Mr. Babu Markus Gomes as Chairman, Mr. Lintu Christopher Gomes as Secretary and Mr. Shiran Sylvester Gomes, Mr. Pankaj Gilbert Costa, Mr. Bipul Lawrence Gomes, Mrs. Papia Rebeiro and Mr. Peter Raton Corraya as members. Rev. Father Frank Quinlivan, Development Director of Notre Dame University Bangladesh officially announced the establishment the Foundation. The Chairman of the Foundation and President of Dhaka Credit Mr. Babu Markus Gomes chaired the event. Among others, former President of Dhaka Credit, Mr. Pankaj Gilbert Costa, Mr. Nirmal Rozario, Executive Board Members and high officials of Dhaka Credit were present.</p><p>The First Executive Committee of the Foundation has initiated the registration process with Registrar of Joint Stock of Company according to the Memorandum of Association and Articles of Association. As per the rules and regulation, the president of Dhaka Credit will hold the position as Chairman of the Foundation while CEO of Dhaka Credit will be the Secretary. In accordance with that, president of Dhaka Credit Pankaj Gilbert Costa is the Chairman of second Executive Committee of the Foundation, Mr. Babu Markus Gomes was the Vice- Chairman, Mr. Liton Tomas Rozario was the Secretary, Mr. Albert Asish Biswas was the Treasurer and Mr. Ignatious Hemanta Corraya, Mr. Peter Raton Corraya and Mrs. Papia Rebeiro were the Executive Board Members. By the enormous effort of this Board, the Foundation achieved the registration on 7th December 2020, under the Registrar of joint Stock Companies and Firms Act 1860 of Bangladesh Government. It is realized that, there is limited scope to take development initiatives in the area of its working area. So, the Executive Committee has taken initiatives to get registration with NGO Affairs Bureau of Bangladesh. The Committee processed for registration with NGOAB. The 3rd Executive Committee of the Foundation obtained NGO Affairs Bureau registration in 2023. Obtaining the NGO AB registration, it opens new window to work in the community through foreign donation. The 3rd Executive Committees are Mr. Ignatious Hemanta Corraya is the Chairman, Mr. Babu Markus Gomes is the Vice- Chairman, Mr. Liton Tomas Rozario is the Secretary, Mr. Albert Asish Biswas is the Treasurer and Mr. Pankaj Gilbert Costa, Mr. Albert Asish Biswas, Mr. Peter Raton Corraya and Mrs. Papia Rebeiro, Mr. Michael John Gomes are the Members.</p>',
                'summary' => null,
                'button_text' => null, 
                'button_link' => null, 
                'attachment_url' => null, 
                'attachment_path' => null, 
                'attachment_name' => null, 
                'attachment_mime' => null, 
                'publish_status' => 'Published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(), 
                'title' => 'Home',
                'slug' => 'home',
                'order' => 4,
                'subtitle' => 'Father Charles Joseph Young Foundation',
                'body' => '<p class="ql-align-justify"><span style="color: rgb(59, 59, 59);">Fr. Charles J. Young Foundation is a non-political, non-profit social service organization, which aims at humanitarian service and progress of society through co-operative research, provide support in general and higher education, provide health services, technical vocational education, training assistance, support to children and youth programs and cultural programs to backward communities especially; tribals, riverine, floating, slum dwellers and other general population. Todays children are the leaders of tomorrow. By providing quality education, we can build a strong nation. Unfortunately, many families lack access to quality education for their children due to economic hardships and lack of awareness. You have the power to create opportunities for these children to receive a quality education and transform their lives. You can proudly contribute to changing a childs life. Sponsor a child now!</span></p>',
                'summary' => null,
                'button_text' => null, 
                'button_link' => null, 
                'attachment_url' => null, 
                'attachment_path' => null, 
                'attachment_name' => null, 
                'attachment_mime' => null, 
                'publish_status' => 'Published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(), 
                'title' => 'About',
                'slug' => 'about',
                'order' => 5,
                'subtitle' => 'Father Charles Joseph Young Foundation',
                'body' => '<p class="ql-align-justify"><br></p><p class="ql-align-justify">Father Charles Joseph Young, CSC, widely known as Fr. Charles J. Young, was a trailblazer in the Credit Union movement in Bangladesh. He founded “The Christian Cooperative Credit Union Limited, Dhaka” to uplift the socio-economic conditions of the Christian community in the country.</p><p class="ql-align-justify">Born on May 3, 1904, in Rochester, New York, USA, Fr. Young took his first vow with the Holy Cross Congregation on July 2, 1925. He earned his Bachelor’s degree from the University of Notre Dame in 1929 and later attended the Foreign Seminary in Washington, becoming a priest in 1933.</p><p class="ql-align-justify">In the same year, Fr. Young embarked on his mission to Bangladesh, engaging in various pastoral and social activities in Dhaka and Mymensingh. At the behest of Most Rev. Lawrence L. Grenar, CSC, Archbishop of Dhaka Diocese, he attended the Coady Institute of St. Francis Xavier University in Canada in 1953 to study co-operatives. In 1955, he returned to Dhaka and established “The Christian Co-Operative Credit Union Ltd., Dhaka” (popularly known as “The Dhaka Credit”), significantly improving the lives of the Christian community.</p><p class="ql-align-justify">Fr. Young’s vision for the Credit Union movement extended across the country, bringing transformative changes to many lives. Today, “The Christian Co-Operative Credit Union Ltd. Dhaka” stands as one of the largest Credit Unions in Bangladesh and South Asia. Fr. Charles J. Young’s contributions have cemented his legacy in the history of the Credit Union Movement in the region. Tragically, he passed away in a road accident on November 14, 1988, in Dhaka and was laid to rest at Tejgaon Holy Rosary Church Graveyard. His death anniversary is commemorated annually with great respect.</p><p class="ql-align-justify">In 2019, led by former President Mr. Babu Markus Gomes, the Executive Committee of The Christian Cooperative Credit Union Limited, Dhaka, decided to establish a foundation to honor Fr. Charles J. Young’s memory and extend development initiatives beyond religious boundaries.</p><p class="ql-align-justify">On August 17, 2019, the “Fr. Charles J. Young Foundation” was established to implement Fr. Young’s dream through research on co-operatives, educational support for underprivileged and meritorious students, technical vocational education, women’s empowerment, and youth development. This non-political, non-profit, and charitable organization continues to honor Fr. Young’s visionary spirit behind Dhaka Credit.</p><p class="ql-align-justify">The Father Charles J. Young Foundation is registered with the NGO Affairs Bureau of Bangladesh (Registration No. NGOAB 3382/18-10-2023) and the Registrar of Joint Stock Companies and Firms under Act 1860 of the Bangladesh Government (Registration No. RJSC S-13463/2020).</p>',
                'summary' => null,
                'button_text' => null, 
                'button_link' => null, 
                'attachment_url' => null, 
                'attachment_path' => null, 
                'attachment_name' => null, 
                'attachment_mime' => null, 
                'publish_status' => 'Published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(), 
                'title' => 'FAQ',
                'slug' => 'faq',
                'order' => 6,
                'subtitle' => 'Frequently Asked Questions',
                'body' => '<p>Father Charles Joseph Young is popularly known as Fr. Charles J. Young who is pioneer of the Credit Union movement in Bangladesh and established ‘The Christian Cooperative Credit Union Limited’ in Dhaka, Bangladesh.</p><h3><strong>1. What is Fr. Charles J. Young Foundation?</strong></h3><p>Answer: Fr. Charles J. Young Foundation is an Bangladeshi National NGO like any other NGOs working in Bangladesh. It established on August 17, 2019 that is a non-political, non-profit &amp; charitable organization that founded with honor of Fr. Charles J. Young, CSC the visionary behind Dhaka Credit.</p><h3><strong>2. What do you mean by Fr. and J. from Fr. Charles J. Young Foundation?</strong></h3><p>Answer: “Fr.” means “Father” and “J.” means “Joseph”.</p><h3><strong>3. Does Fr. Charles J. Young Foundation is an NGO?</strong></h3><p>Answer: Yes, it is an NGO as well as it has registered under joint stock company. Registration numbers RJSC S-13463/2020 and NGOAB 3382/18-10-2023.</p><h3><strong>4. Why was Fr. Charles J. Young Foundation established?</strong></h3><p>Answer: Father Charles J. Young Foundation was established for community development and poverty elimination in Bangladesh.</p><h3><strong>5. Who is the owner of Fr. Charles J. Young Foundation?</strong></h3><p>Answer: No individual / person is the owner of the Foundation. This foundation is operated by an Executive Board. This Foundation was established by the Christian Cooperative Credit Union Ltd (CCCUL), popularly known as the “Dhaka Credit”.</p><h3><strong>6. Does anybody give donation to Fr. Charles J. Young Foundation and what is the minimum amount?</strong></h3><p>Answer: Yes, anybody can give donation to Fr. Charles J. Young Foundation. You can give any amount monthly or at a time.</p><h3><strong>7. Is there any bank account operate for Fr. Charles J. Young Foundation?</strong></h3><p>Answer: Yes, account name is Fr. Charles J. Young Foundation at Bank Asia Ltd (Scotia Branch). To donate, please click on “Donate Now” button.</p><h3><strong>8. Do external audit complete for Fr. Charles J. Young Foundation?</strong></h3><p>Answer: Yes, Chartered Accounting Firm complete the audit by yearly basis.</p><h3><strong>9. How the administration costs for Father Charles J. Young Foundation are maintained now?</strong></h3><p>Answer: Local donations are being collected. We have a few good wishers who provided the ‘seed money’ by generating income from the ‘seed money’ the administration costs are meet. The Foundation is trying to get foreign donation. Hope after getting the fund from the donor(s), the management cost will be covered.</p>',
                'summary' => null,
                'button_text' => null, 
                'button_link' => null, 
                'attachment_url' => null, 
                'attachment_path' => null, 
                'attachment_name' => null, 
                'attachment_mime' => null, 
                'publish_status' => 'Published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(), 
                'title' => 'Mission Vision',
                'slug' => 'mission-vision',
                'order' => 7,
                'subtitle' => 'What we are aiming for?',
                'body' => '<h3><strong>Vision Statement:</strong></h3><p>Empowering individuals and communities to achieve their fullest potential building an inclusive and empowered community for sustainable growth and development.</p><h3><strong>Mission</strong></h3><p>Fr. Charles J. Young Foundation is a non-political, non-profit organization which aims to empower the community through providing assistance for education, health, technical vocational education, skill development training, cultural programs, co-operative research and especially youth development of backward &amp; unaware communities including tribals, riverine, floating, slum dwellers irrespective of caste, creed &amp; religion.</p><h3><strong>We will fulfill our mission through;</strong></h3><ul><li>Support to the poor and oppressed</li><li>Build awareness</li><li>Child and Youth development</li><li>Skill development initiatives</li><li>Gender equality/empowerment</li></ul><h3><strong>Values</strong></h3><p>Values are the beliefs and principles that move forward upto the results.Fr. Charles J. Young Foundation believes, keeps it in mind to achieving its goals through;</p><ul><li>Humility</li><li>Respect</li><li>Integrity</li><li>Commitment</li><li>Results oriented</li></ul>',
                'summary' => null,
                'button_text' => null, 
                'button_link' => null, 
                'attachment_url' => null, 
                'attachment_path' => null, 
                'attachment_name' => null, 
                'attachment_mime' => null, 
                'publish_status' => 'Published',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(), 
                'title' => 'Activities',
                'slug' => 'activities',
                'order' => 8,
                'subtitle' => 'Did we meet your expectations?',
                'body' => '<p class="ql-align-justify">From sponsoring scholarships and stipends for deserving students to promoting research in the Credit Union movement, the foundation is committed to academic excellence and the advancement of cooperative principles.</p><p class="ql-align-justify">The foundation’s core objectives encompass a spectrum of benevolent activities. From sponsoring scholarships and stipends for deserving students to promoting research in the Credit Union movement, the foundation is committed to academic excellence and the advancement of cooperative principles. Additionally, its humanitarian endeavors extend to providing essential medical treatment to the underprivileged, imparting vocational training to those in need, and supporting nation-building, cultural, and sports activities. Emphasizing inclusivity, the foundation is dedicated to empowering children, youth, and women while extending support to educational and vocational institutions. With a broad vision of compassionate benevolence. Fr. Charles J. Young Foundation serves as a beacon of compassion and social progress, guided by its commitment to the well-being and development of individuals and society as a whole.</p><h4><strong>Focuses Area</strong></h4><p><strong>Education</strong>- different program, photo, impact story</p><ul><li>Stipend</li><li>Education materials</li><li>Early childhood care and development</li><li>Awareness on social safety &amp; security</li><li>Assist to establish educational and technical institute</li><li>Technical and Vocational Education and training</li><li>Protect children and empowering young and women Health</li></ul><h3><strong>Health</strong></h3><ul><li>Emergency treatment support</li><li>Medical Check up</li><li>Awareness on health and nutrition</li><li>Awareness on different issues Youth Development</li></ul><h4><strong>Youth Development</strong></h4><ul><li>Assist to select right career</li><li>Linkage with financial institute</li><li>Uphold moral values</li><li>Cultural practice</li><li>Seminar on freelancing</li><li>Essay and debate completion</li><li>Seminar for nursing admission</li></ul><h4><strong>Cooperative Centered Research</strong></h4><ul><li>Socio-Economic Baseline Survey</li><li>Cooperative Research and promoting Credit Union</li></ul><h4><strong>Emergency Support</strong></h4><p>Food support in COVID period</p><p>Mosquito net support in Dengue Crisis – 2023</p>',
                'summary' => null,
                'button_text' => null, 
                'button_link' => null, 
                'attachment_url' => null, 
                'attachment_path' => null, 
                'attachment_name' => null, 
                'attachment_mime' => null, 
                'publish_status' => 'Published',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
